--ĐỀ THI LUYỆN THI 01 CUỐI MÔN COM2034
--(thời gian 60 phút)
--Câu 1 (1.5 điểm): Tạo cơ sở dữ liệu DATHANG gồm 3 bảng. 
--MATHANG (MaH, TenH, LoaiH, DVTinh )
--DONHANG (SoDH, NgayDH, NgayGH)
--CTDH (SoDH, MaH, SoLuong, DonGia)
CREATE DATABASE DATHANG
--BẢNG MATHANG
IF OBJECT_ID('MATHANG') IS NOT NULL
DROP TABLE MATHANG
GO 
CREATE TABLE MATHANG(
	MAH VARCHAR(20) NOT NULL,
	TENH NVARCHAR(30) NULL,
	LOAIH NVARCHAR(30) NULL,
	DVTINH NVARCHAR(20) NULL,
	CONSTRAINT PK_MATHANG PRIMARY KEY (MAH)
)
--BANG DONHANG
IF OBJECT_ID('DONHANG') IS NOT NULL
DROP TABLE DONHANG
GO 
CREATE TABLE DONHANG(
	SODH VARCHAR(20) NOT NULL,
	NGAYDH DATETIME NULL,
	NGAYGN DATETIME NULL,
	CONSTRAINT PK_DONHANG PRIMARY KEY (SODH)
)
--BẢNG CTDH
IF OBJECT_ID('CTDH') IS NOT NULL
DROP TABLE CTDH
GO 
CREATE TABLE CTDH(
	SODH VARCHAR(20) NOT NULL,
	MAH VARCHAR(20) NOT NULL,
	SOLUONG INT NULL,
	DONGIA MONEY NULL,
	CONSTRAINT PK_CTDH PRIMARY KEY (SODH, MAH),
	CONSTRAINT FK_CTDH_MATHANG FOREIGN KEY (MAH) REFERENCES MATHANG,
	CONSTRAINT FK_CTDH_DONHANG FOREIGN KEY (SODH) REFERENCES DONHANG
)
--Câu 2 (3 điểm): Chèn thông tin vào các bảng
--Tạo Stored Procedure (SP) với các tham số đầu vào phù hợp.
--SP thứ nhất thực hiện chèn dữ liệu vào bảng MATHANG.
--SP thứ hai thực hiện chèn dữ liệu vào bảng DONHANG.
--SP thứ ba thực hiện chèn dữ liệu vào bảng CTDH.
--Yêu cầu mỗi SP phải kiểm tra tham số đầu vào. Với các cột không chấp nhận thuộc tính Null.
--Với mỗi SP viết 3 lời gọi thành công.
--BẢNG MATHANG
IF OBJECT_ID('SP_MATHANG') IS NOT NULL
DROP PROC SP_MATHANG
GO
CREATE PROC SP_MATHANG
@MAH VARCHAR(20) ,@TENH NVARCHAR(30) NULL,@LOAIH NVARCHAR(30),@DVTINH NVARCHAR(20)
AS IF @MAH IS NULL OR @TENH IS NULL OR @LOAIH IS NULL OR @DVTINH IS NULL
PRINT N'VUI LÒNG NHẬP ĐỦ DỮ LIỆU'
INSERT MATHANG VALUES(@MAH, @TENH, @LOAIH, @DVTINH)
EXEC SP_MATHANG 'MH1', N'ACER', N'MÁY TÍNH', N'CÁI'
EXEC SP_MATHANG 'MH2', N'IPHONE 13 PRO MAX', N'ĐIỆN THOẠI', N'CÁI'
EXEC SP_MATHANG 'MH3', N'JBL', N'LOA', N'CÁI'
SELECT *FROM MATHANG
--BẢNG DONHANG
IF OBJECT_ID('SPDONHANG') IS NOT NULL 
DROP PROC SPDONHANG
GO
CREATE PROC SPDONHANG
@SODH VARCHAR(20) ,
	@NGAYDH DATETIME ,
	@NGAYGN DATETIME 
AS IF @SODH IS NULL OR @NGAYDH IS NULL OR @NGAYGN IS NULL
PRINT N'VUI LÒNG NHẬP ĐỦ DỮ LIỆU'
INSERT DONHANG VALUES (@SODH,@NGAYDH,@NGAYGN)
EXEC SPDONHANG '1712', '05/17/2022', '05/20/2022'
EXEC SPDONHANG '1705', '6/6/2022', '6/10/2022'
EXEC SPDONHANG '0508', '6/1/2022', '6/5/2022'
SELECT *FROM DONHANG
--BẢNG CTHD
IF OBJECT_ID('SP_CTDH') IS NOT NULL
DROP PROC SP_CTDH
GO
CREATE PROC SP_CTDH
@SODH VARCHAR(20),
	@MAH VARCHAR(20) ,
	@SOLUONG INT ,
	@DONGIA MONEY 
AS IF @SODH IS NULL OR @MAH IS NULL OR @SOLUONG IS NULL OR @DONGIA IS NULL
PRINT N'VUI LÒNG NHẬP ĐỦ DỮ LIỆU'
INSERT CTDH VALUES(@SODH,@MAH,@SOLUONG,@DONGIA) 
EXEC SP_CTDH '1712', 'MH1', 2, 22000000
EXEC SP_CTDH '0508','MH2', 5, 31000000
EXEC SP_CTDH '1705','MH3', 7, 2500000
SELECT * FROM CTDH
--Câu 3 (2 điểm): Viết Hàm
--Viết hàm các tham số đầu vào tương ứng với các cột của bảng MATHANG. Hàm này trả về MaH thỏa mãn các giá trị được truyền tham số.
IF OBJECT_ID('FUNC_MATHANG') IS NOT NULL
DROP FUNCTION FUNC_MATHANG
GO
CREATE FUNCTION FUNC_MATHANG
(
@MAH VARCHAR(20) ,
	@TENH NVARCHAR(30) ,
	@LOAIH NVARCHAR(30) ,
	@DVTINH NVARCHAR(20)
)
RETURNS VARCHAR(20)
BEGIN
RETURN (SELECT MAH FROM DONHANG WHERE MAH = @MAH AND TENH = @TENH AND LOAIH = @LOAIH AND @DVTINH = DVTINH)
END

DECLARE @MAH VARCHAR(20)
SET @MAH= DBO.FUNC_MATHANG ('MH1', N'ACER', N'MÁY TÍNH', N'CÁI')
SELECT @MAH AS MAH
--Câu 4 (1.5 điểm): Tạo View 
--Tạo View lưu thông tin của TOP 5 có giá trị đơn hàng lớn nhất, gồm các thông tin sau: MaH, TenH, LoaiH, NgayDH, NgayGH, SoLuong, DonGia, “Gia Tri Max”. 
GO 
alter VIEW VIEW_GIATRIDNLN
AS
SELECT TOP 5 MATHANG.MAH , MATHANG.TENH, MATHANG.LOAIH, DONHANG.NGAYDH, DONHANG.NGAYGN, CTDH.SOLUONG, CTDH.DONGIA, (SOLUONG * DONGIA) AS GTDHLN
FROM MATHANG INNER JOIN CTDH ON MATHANG.MAH= CTDH.MAH
			INNER JOIN DONHANG ON MATHANG.MAH = DONHANG.SODH
GROUP BY MATHANG.MAH , MATHANG.TENH, MATHANG.LOAIH, DONHANG.NGAYDH, DONHANG.NGAYGN, CTDH.SOLUONG, CTDH.DONGIA
ORDER BY GTDHLN DESC
select * from VIEW_GIATRIDNLN
--Câu 5 (2 điểm): Viết thủ tục
--Viết một SP nhận một tham số đầu vào là SoLuong. SP này thực hiện thao tác xóa thông tin mặt hàng và đơn hàng tương ứng.
--Yêu cầu: Sử dụng giao dịch trong thân SP, để đảm bảo tính toàn vẹn dữ liệu khi một thao tác xóa thực hiện không thành công.
IF OBJECT_ID('PROC_XOA') IS NOT NULL
DROP PROC PROC_XOA
GO 
CREATE PROC PROC_XOA
@SOLUONG INT 
AS IF @SOLUONG IS NULL
PRINT N'VUI LÒNG NHẬP ĐỦ DỮ LIỆU'
ELSE
BEGIN 

DELETE CTDH WHERE (SOLUONG)>@SOLUONG

END 

EXEC PROC_XOA 2
SELECT * FROM CTDH